---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: open-cluster-management-observability
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 10m
    route:
      group_by: ['alertname', 'cluster']
      group_wait: 60s
      group_interval: 10m
      repeat_interval: 6h
      receiver: 'dev-notifications'
    receivers:
    - name: 'dev-notifications'
      slack_configs:
      - channel: '#openshift-alerts-channel'
        api_url_file: /etc/alertmanager/secrets/slack-webhook/webhook-url
        send_resolved: true
        title: '[DEV] {{ .CommonAnnotations.summary }}'
        text: '{{ .CommonAnnotations.description }}'
type: Opaque
